import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { NextAuthProviders } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <div className={inter.className}>
        <NextAuthProviders>
          <div className="max-w-4xl mx-auto" >
            <Navbar />
            {children}
          </div>
        </NextAuthProviders>
      
        </div>
  
  );
}
